Fix error due to enable of `importsNotUsedAsValues`
Fix the following error due to Deno v1.4.0
error: TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { Matcher, Matchers } from "./matchers.ts";